# Generated by Django 5.0.6 on 2024-07-06 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PalafitosApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='categoria',
            field=models.CharField(choices=[('primeraClase', 'primeraClase'), ('claseEjecutiva', 'claseEjecutiva'), ('economicaPremium', 'economicaPremium'), ('economica', 'economica')], default='economica', max_length=100),
        ),
        migrations.AddField(
            model_name='cliente',
            name='metodoPago',
            field=models.CharField(choices=[('credito', 'credito'), ('debito', 'debito'), ('paypal', 'paypal'), ('transferencia', 'transferencia')], default='debito', max_length=100),
        ),
    ]
