# Generated by Django 5.0.6 on 2024-07-08 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PalafitosApp', '0002_cliente_categoria_cliente_metodopago'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('monto', models.CharField(max_length=9)),
            ],
        ),
    ]
