# Generated by Django 5.0.6 on 2024-07-08 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PalafitosApp', '0003_donacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donacion',
            name='monto',
            field=models.CharField(max_length=999),
        ),
    ]
